services:
  n8n:
    build: .
    environment:
      - 'SERVICE_FQDN_N8N_5678:${SERVICE_FQDN_N8N}'
      - 'N8N_EDITOR_BASE_URL=https://n8n.${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=https://n8n.${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=Europe/Berlin'
      - 'TZ=${TZ:-Europe/Berlin}'
    volumes:
      - u4s8g48ws0kowo4oscwvkw_n8n-data:/home/node/.n8n # <-- THIS IS THE CRITICAL CHANGE
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10

# This tells Docker "don't create a new volume,
# use the existing one with this exact name"
volumes:
  u4s8g48ws0kowo4oscwvkw_n8n-data:
    external: true
